# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-21 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import squeeze.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqueezeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_user_email', models.EmailField(max_length=254)),
                ('real_user_name', models.CharField(max_length=120)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('notified_on', models.DateTimeField(blank=True, null=True)),
                ('random_key', models.CharField(default=squeeze.models.random_key, max_length=40)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
    ]
